# Generated by Django 2.1.3 on 2018-12-03 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=50)),
                ('position', models.CharField(max_length=50)),
                ('date_applied', models.DateField(blank=True, null=True)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('p', 'In Progress'), ('a', 'Applied'), ('i', 'Interviewing'), ('d', 'Denied'), ('r', 'Remove')], default='p', help_text='Application status', max_length=1)),
            ],
            options={
                'ordering': ['status'],
            },
        ),
    ]
