# Generated by Django 2.1.3 on 2018-12-04 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(blank=True, choices=[('p', 'In Progress'), ('a', 'Applied'), ('i', 'Interviewing'), ('o', 'Offer'), ('d', 'Denied'), ('r', 'Remove')], default='p', help_text='Application status', max_length=1),
        ),
    ]
