# Generated by Django 2.1.3 on 2018-12-16 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0003_application_owner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='application',
            options={'ordering': ['company'], 'permissions': (('can_view_all_applications', 'View all applications'),)},
        ),
    ]
