# Generated by Django 2.1.3 on 2018-12-17 19:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_name', models.CharField(max_length=50)),
                ('entry_text', models.CharField(max_length=280)),
                ('entry_order', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ProfileSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_name', models.CharField(max_length=50)),
                ('section_order', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='profileinfo',
            name='entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prof_profile.ProfileSection'),
        ),
    ]
